### ISSUE TITLE
Change URL

### ISSUE THREAD

**Issue by StoneMonarch** [Voidustries/Poly#35]
Change goog.le URL to https://www.voidustries.ca/Poly/

**Comment by gponimansky** [comment]
Change URL to https://www.voidustries.ca/poly/

**Comment by StoneMonarch** [comment]
![screenshot_20180910-013248_chrome](https://user-images.githubusercontent.com/35647358/45278108-9eae0200-b499-11e8-8a9c-818f4879246d.jpg)
Not fixed

**Comment by gponimansky** [comment]
I know, the description should be updated, and it is fixed in all projects now. #36

**Comment by StoneMonarch** [comment]
URL must be 'P' not 'p' due to the fact were hosting on Github. The URL Github assigns is based on the repo name. Repo name is 'Poly' so the url MUST be https://www.voidustries.ca/Poly/ all links will be broken otherwise

**Comment by gponimansky** [comment]
Issue closed with #37
