### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by gponimansky** [Voidustries/Poly#4]
Possibly update the Readme.md, as the current images replacing titles looks off in mobile/tablet screens. 

Mobile:  

![Example One](http://i.imgur.com/Okmw4Qa.png)

---

Desktop:  

![Example Two](http://i.imgur.com/OoXg0KU.png)

**Comment by StoneMonarch** [comment]
I see what you are saying. I like the fact that they do stretch the width of the document but they dont look good on mobile, Possibly look into some sort of fade effect and have the devider centered. Not a top priority, will look into it later.

**Comment by StoneMonarch** [comment]
Fixed with commit: 88dc13d
